### ISSUE TITLE
Extracted dashboards yaml file uses things/variables names rather than UIDs

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-cloud-cli#96]
If I extract a Dashboard its widgets are linked to Things and Variables based on their names rather than UID.
I would expect the Thing ID and Variable ID to be listed instead.
This could be useful to retrieve full details of a dashboard, not just the labels.
Any reason why it's just like this?

__Current structure__
```yaml
- height: 4
    height_mobile: 4
    name: Switch A
    options:
        frameless: false
        mode: Color 2
        showThing: false
    type: LED
    variables:
      - thing_id: sOnOff
        variable_id: switch_A
    width: 4
    width_mobile: 4
    x: 0
    x_mobile: 0
    "y": 0
    y_mobile: 0
```

__Full structure__
```
- height: 4
    height_mobile: 4
    name: Switch A
    options:
        frameless: false
        mode: Color 2
        showThing: false
    type: LED
    variables:
      - thing_id: 0bbafafc-2ac3-4d10-9620-34f8fb284701
        thing_name: SonOff
        variable_id: d0be0122-24cd-4a6d-99f5-793e21ac34a1
        variable_id: switch_A
    width: 4
    width_mobile: 4
    x: 0
    x_mobile: 0
    "y": 0
    y_mobile: 0
```
